from __future__ import annotations

from io import BytesIO
from xml.sax.saxutils import escape

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from docx.shared import Inches, Pt, RGBColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from app.models import ResearchRun, Source


def report_to_docx(run: ResearchRun) -> bytes:
    report = _require_report(run)
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.9)
    section.bottom_margin = Inches(0.9)
    section.left_margin = Inches(1.0)
    section.right_margin = Inches(1.0)

    title = document.add_heading("Research report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    question = document.add_paragraph()
    question.add_run("Question: ").bold = True
    question.add_run(run.query)

    document.add_heading("Executive summary", level=1)
    document.add_paragraph(report.executive_summary.strip())

    document.add_heading("Findings", level=1)
    if not report.findings:
        document.add_paragraph("None recorded.")
    for index, finding in enumerate(report.findings, start=1):
        document.add_heading(f"{index}. {finding.claim}", level=2)
        document.add_paragraph(finding.evidence.strip())
        meta = document.add_paragraph()
        meta.add_run("Confidence: ").bold = True
        meta.add_run(f"{finding.confidence} — {finding.confidence_rationale}")
        cites = document.add_paragraph()
        cites.add_run("Sources: ").bold = True
        cites.add_run(", ".join(finding.source_ids) if finding.source_ids else "none")

    document.add_heading("Gaps and risks", level=1)
    if report.gaps_and_risks:
        for item in report.gaps_and_risks:
            document.add_paragraph(item, style="List Bullet")
    else:
        document.add_paragraph("None recorded.")

    document.add_heading("Bibliography", level=1)
    if report.bibliography:
        for source in report.bibliography:
            paragraph = document.add_paragraph(style="List Bullet")
            paragraph.add_run(f"[{source.id}] {source.title}").bold = True
            paragraph.add_run(" — ")
            paragraph.add_run(source.snippet)
            if source.url:
                paragraph.add_run(" ")
                _add_hyperlink(paragraph, source.url, source.url)
    else:
        document.add_paragraph("None recorded.")

    if run.plan:
        document.add_heading("Research plan", level=1)
        objective = document.add_paragraph()
        objective.add_run("Objective: ").bold = True
        objective.add_run(run.plan.objective)
        for question_item in run.plan.sub_questions:
            document.add_paragraph(question_item, style="List Bullet")

    if run.iterations:
        document.add_heading("Investigation log", level=1)
        for item in run.iterations:
            queries = "; ".join(search.query for search in item.searches) or "none"
            gaps = ", ".join(item.assessment.gaps) or "none"
            document.add_paragraph(
                f"Iteration {item.iteration}: searched {queries}. "
                f"Gaps: {gaps}. Sufficient: {item.assessment.sufficient}.",
                style="List Bullet",
            )

    footer = document.add_paragraph()
    footer_run = footer.add_run(
        "Generated by Autonomous Research Agent. Review sources before sharing."
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def report_to_pdf(run: ResearchRun) -> bytes:
    report = _require_report(run)
    buffer = BytesIO()
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=18,
        spaceAfter=8,
        leading=22,
    )
    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading1"],
        fontSize=13,
        spaceBefore=12,
        spaceAfter=6,
    )
    subheading_style = ParagraphStyle(
        "ReportSubheading",
        parent=styles["Heading2"],
        fontSize=11,
        spaceBefore=8,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        fontSize=10,
        leading=14,
        spaceAfter=6,
    )
    muted_style = ParagraphStyle(
        "ReportMuted",
        parent=body_style,
        textColor="#555555",
        fontSize=8,
        spaceBefore=16,
    )

    story = [
        Paragraph("Research report", title_style),
        Paragraph(f"<b>Question:</b> {escape(run.query)}", body_style),
        Paragraph("Executive summary", heading_style),
        Paragraph(
            escape(report.executive_summary.strip()).replace("\n", "<br/>"), body_style
        ),
        Paragraph("Findings", heading_style),
    ]
    if not report.findings:
        story.append(Paragraph("None recorded.", body_style))
    for index, finding in enumerate(report.findings, start=1):
        cites = ", ".join(finding.source_ids) if finding.source_ids else "none"
        story.extend(
            [
                Paragraph(escape(f"{index}. {finding.claim}"), subheading_style),
                Paragraph(escape(finding.evidence.strip()), body_style),
                Paragraph(
                    f"<b>Confidence:</b> {escape(finding.confidence)} — {escape(finding.confidence_rationale)}",
                    body_style,
                ),
                Paragraph(f"<b>Sources:</b> {escape(cites)}", body_style),
            ]
        )

    story.append(Paragraph("Gaps and risks", heading_style))
    story.append(_bullet_list(report.gaps_and_risks or ["None recorded"], body_style))

    story.append(Paragraph("Bibliography", heading_style))
    if report.bibliography:
        story.append(
            _bullet_list(
                [_pdf_source_line(source) for source in report.bibliography], body_style
            )
        )
    else:
        story.append(Paragraph("None recorded.", body_style))

    if run.plan:
        story.append(Paragraph("Research plan", heading_style))
        story.append(
            Paragraph(f"<b>Objective:</b> {escape(run.plan.objective)}", body_style)
        )
        story.append(_bullet_list(run.plan.sub_questions, body_style))

    if run.iterations:
        story.append(Paragraph("Investigation log", heading_style))
        log_items = []
        for item in run.iterations:
            queries = "; ".join(search.query for search in item.searches) or "none"
            gaps = ", ".join(item.assessment.gaps) or "none"
            log_items.append(
                f"Iteration {item.iteration}: searched {queries}. "
                f"Gaps: {gaps}. Sufficient: {item.assessment.sufficient}."
            )
        story.append(_bullet_list(log_items, body_style))

    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            "Generated by Autonomous Research Agent. Review sources before sharing.",
            muted_style,
        )
    )

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="Research report",
        author="Autonomous Research Agent",
    )
    document.build(story)
    return buffer.getvalue()


def _require_report(run: ResearchRun):
    if run.report is None:
        raise ValueError("Report is not ready to export")
    return run.report


def _bullet_list(items: list[str], style: ParagraphStyle) -> ListFlowable:
    return ListFlowable(
        [
            ListItem(
                Paragraph(escape(item), style), leftIndent=12, bulletColor="#333333"
            )
            for item in items
        ],
        bulletType="bullet",
        start="•",
        leftIndent=12,
        bulletFontName="Helvetica",
        bulletFontSize=10,
    )


def _pdf_source_line(source: Source) -> str:
    url = f" ({source.url})" if source.url else ""
    return f"[{source.id}] {source.title}{url} — {source.snippet}"


def _add_hyperlink(paragraph, url: str, text: str) -> None:
    part = paragraph.part
    relationship_id = part.relate_to(url, RT.HYPERLINK, is_external=True)
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), relationship_id)
    run = OxmlElement("w:r")
    run_properties = OxmlElement("w:rPr")
    color = OxmlElement("w:color")
    color.set(qn("w:val"), "0563C1")
    underline = OxmlElement("w:u")
    underline.set(qn("w:val"), "single")
    run_properties.append(color)
    run_properties.append(underline)
    run.append(run_properties)
    text_element = OxmlElement("w:t")
    text_element.text = text
    run.append(text_element)
    hyperlink.append(run)
    paragraph._p.append(hyperlink)
